name: 'hcltm'
description: 'An action to run hcltm commands in your GitHub Workflows'
author: 'Christian @xntrik Frichot'
inputs:
  command:
    description: 'What hcltm command to run - either validate, dashboard or dfd'
    required: true
    default: 'validate'
  files:
    description: 'files to process with hcltm'
    required: true
    default: '*'
  outdir:
    description: 'outdir, used with dashboard command'
    required: false
  dashboard-template:
    description: 'dashboard-template, used with the dashboard command'
    required: false
    default: ''
  dashboard-filename:
    description: 'dashboard-filename, used with the dashboard command'
    required: false
    default: ''
  dashboard-html:
    description: 'dashboard-html, used with the dashboard command. Must be a string of true or false'
    required: false
    default: 'false'
  threatmodel-template:
    description: 'threatmodel-template, used with the dashboard command'
    required: false
    default: ''
  dfd-type:
    description: 'dfd-type, used with the dfd command. Must be a string of png, svg or dot. We default to PNG output'
    required: false
    default: 'png'
  outext:
    description: 'outext, used with the dashboard command to pass the -out-ext flag'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://xntrik/hcltm-action:v0.0.8'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.files }}
    - ${{ inputs.outdir }}
    - ${{ inputs.dashboard-template }}
    - ${{ inputs.dashboard-filename }}
    - ${{ inputs.dashboard-html }}
    - ${{ inputs.threatmodel-template }}
    - ${{ inputs.dfd-type }}
    - ${{ inputs.outext }}
