name: 'hcltm'
description: 'An action to run hcltm commands in your GitHub Workflows'
author: 'Christian @xntrik Frichot'
inputs:
  command:
    description: 'What hcltm command to run'
    required: true
    default: 'validate'
  files:
    description: 'files to process with hcltm'
    required: true
    default: '*'
  outdir:
    description: 'outdir, used with dashboard command'
    required: false
runs:
  using: 'docker'
  image: 'docker://xntrik/hcltm-action:latest'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.files }}
    - ${{ inputs.outdir }}
